export const CREATE_STUDIO = "CREATE_STUDIO";
export const VIEW_STUDIO = "VIEW_STUDIO";
export const VIEW_ALL_STUDIOS = "VIEW_ALL_STUDIOS";
export const VIEW_STUDIO_WITH_ANIME = "VIEW_STUDIO_WITH_ANIME";
